---

- name: Install required system packages.
  apt: pkg={{ item }} state=installed
  with_items:
    - redis-server
  become: yes
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - redis

- name: Copy redis conf file
  become: yes
  become_user: "{{ ansible_user }}"
  notify:
    - restart redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0755
  tags:
    - setup
    - redis
