---

- name: Check Yajl installation
  stat: path=/home/{{ ansible_user }}/.local/lib/libyajl.so.2.1.1
  register: yajl_exists
  tags:
    - setup
    - trellio

- name: Install yajl
  include: roles/yajl/tasks/main.yml
  when: yajl_exists.stat.exists == False
  tags:
    - setup
    - trellio

#- name: Check Python 3.6 Installed
#  stat: path=/usr/local/bin/python3.6
#  register: py36_exists
#  tags:
#    - setup
#    - trellio
#    - python

- name: Add python3.6 repository
  sudo: yes
  apt_repository: repo='ppa:jonathonf/python-3.6' state=present
  tags:
    - setup
    - trellio
    - python

- name: update apt-get
  apt: update_cache=yes
  sudo: yes
  tags:
    - setup
    - trellio
    - python



#- name: Download Python
#  unarchive:
#    copy: no
#    src: "https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz"
#    dest: /tmp/
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    mode: 0775
#  sudo: yes
#  when: py36_exists.stat.exists == False
#  tags:
#    - setup
#    - trellio
#    - python
#
#- name: Install Python
#  shell: cd /tmp/Python-3.6.2 && ./configure --prefix=/usr/local && make altinstall chdir=/tmp/Python-3.6.2/ creates=/usr/local/bin/python3.6
#  sudo: yes
#  when: py36_exists.stat.exists == False
#  tags:
#    - setup
#    - trellio
#    - python


- name: Install python3.6 and required packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python3.6
    - python3.6-dev
    - python3-pip
  sudo: yes
  tags:
    - setup
    - trellio
    - python

- name: Installing Virtualenv
  pip: name=virtualenv
  sudo: yes
  ignore_errors: yes
  tags:
    - setup
    - trellio
    - python

- name: Create Virtualenv & upgrade pip
  pip:
     name={{ item.name }}
     virtualenv=/home/{{ ansible_user }}/venv
     virtualenv_python=python3.6
  with_items:
     - name: pip --upgrade
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - trellio
    - python

- name: Installing trellio
  shell: /home/{{ ansible_user }}/venv/bin/pip install trellio --upgrade --no-cache-dir
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - trellio

- name: Copy trellio registry upstart file
  sudo: yes
  notify:
    - reload systemctl
    - disable trellio
    - enable trellio
    - restart trellio
  template: src=trellio.service.j2 dest=/etc/systemd/system/trellio.service owner="{{ ansible_user }}" group="{{ ansible_user }}" backup=yes mode=0644
  tags:
    - registry
