# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-17 11:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0002_auto_20170217_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.IntegerField(blank=True, default=1487330925, null=True)),
                ('updated_on', models.IntegerField(blank=True, default=1487330925, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deployment_server', models.CharField(choices=[('On Service Host', 'On Service Host'), ('Remote Host', 'Remote Host')], default='On Service Host', max_length=20)),
                ('slaves', models.IntegerField(default=0)),
                ('database_extension', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='PostgresNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.IntegerField(blank=True, default=1487330925, null=True)),
                ('updated_on', models.IntegerField(blank=True, default=1487330925, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('database_name', models.CharField(max_length=100, unique=True)),
                ('database_host', models.CharField(max_length=100)),
                ('database_port', models.IntegerField(default=5432)),
                ('database_user', models.CharField(max_length=100)),
                ('database_password', models.CharField(max_length=100)),
                ('optional_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databases.PostgresNode')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postgres',
            unique_together=set([('deployment_server', 'slaves', 'database_extension')]),
        ),
        migrations.AlterUniqueTogether(
            name='postgresnode',
            unique_together=set([('server', 'database_port')]),
        ),
    ]
