# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-21 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20170221_1020'),
        ('databases', '0002_auto_20170219_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.IntegerField(blank=True, default=1487672395, null=True)),
                ('updated_on', models.IntegerField(blank=True, default=1487672395, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('database_name', models.CharField(max_length=100, unique=True)),
                ('database_host', models.CharField(default='0.0.0.0', max_length=100)),
                ('database_port', models.IntegerField(default=6379)),
                ('database_user', models.CharField(blank=True, max_length=100, null=True)),
                ('database_password', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databases.RedisNode')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.AlterField(
            model_name='postgres',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='postgres',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='postgresnode',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='postgresnode',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='redisnode',
            unique_together=set([('server', 'database_port')]),
        ),
    ]
