# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuser',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487495531, null=True),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487495531, null=True),
        ),
    ]
