---

- name: reload cache
  apt: update_cache=yes
  sudo: yes

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes