---

- name: Add postgres repository
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present
  tags:
    - postgres
    - setup

- name: Add postgres repository key
  sudo: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present validate_certs=no
  tags:

    - postgres
    - setup

- name: update apt-get
  apt: update_cache=yes
  sudo: yes
  tags:
    - postgres
    - setup

- name: ensure packages are installed
  sudo: yes
  apt: name={{item}}
  with_items:
    - postgresql-9.6
    - libpq-dev
    - python-psycopg2
  tags:
    - postgres
    - setup

- name: install postgis
  sudo: yes
  apt: name={{ item }}
  with_items:
    - postgresql-9.6-postgis-2.3
  tags:
    - postgis

- name: ensure database is created
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
  register: create_postgres_db
  tags:
    - postgres
    - setup

- name: ensure user has access to database
  become: yes
  become_user: postgres
  postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_pass }} priv=ALL
  tags:
    - postgres
    - setup


- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  notify: restart postgres
  tags:
    - postgres
    - setup


- name: Copy sql file
  sudo: yes
  template: src=db.sql.j2 dest=/tmp/db.sql owner=root group=root mode=0755
  tags:
    - postgres


- name: execute sql file
  shell: psql -d {{ db_name }} -a -f /tmp/db.sql
  with_items: sql
  become: yes
  become_user: postgres
  tags:
    - postgres

#- name: Delete sql script
#  file: path="/tmp/db.sql" state=absent
#  sudo: yes
#  tags:
#    - postgres

- name: grant user permissions on all tables
  become: yes
  become_user: postgres
  command: psql -d {{ db_name }} -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ db_user }};"
  tags:
    - postgres

- name: Copy pg_hba.conf file
  sudo: yes
  notify:
    - restart postgres
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.6/main/pg_hba.conf owner=root group=root mode=0755
  tags:
    - setup
    - postgres

- name: Copy postgresql.conf file
  sudo: yes
  notify:
    - restart postgres
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.6/main/postgresql.conf owner=root group=root mode=0755
  tags:
    - setup
    - postgres
