---

- name: Install postgres
  include: roles/postgres/tasks/main.yml
  tags:
    - setup
    - postgres

- name: setup xauth and createsuperuser
  shell: |
    cd {{ project_root }}/{{ project_name }}
    /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py makemigrations xauth
    /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py migrate
  notify:
    - restart uwsgi
  tags:
    - setup
    - trellioadmin

- name: trellioadmin copy settings.py
  template: src=settings.py.j2 dest={{ project_root }}/{{ project_name }}/{{ project_name }}/settings.py
  sudo: yes
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: creating app directories
  file: path={{ project_root }}/{{ project_name }}/apps/{{ item.service }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0777 state=directory
  sudo: yes
  with_items:
    - "{{ services }}"
  tags:
    - trellioadmin

- name: creating apps
  shell: /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py startapp {{ item.service }} {{ project_root }}/{{ project_name }}/apps/{{ item.service }}
  with_items:
    - "{{ services }}"
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: running inspectdb command
  shell: /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py inspectdb --database={{ item.service }} > {{ project_root }}/{{ project_name }}/apps/{{ item.service }}/models.py
  with_items:
    - "{{ services }}"
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: migrating db changes
  shell: |
    /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py makemigrations
    /home/{{ ansible_user }}/venv/bin/python {{ project_root }}/{{ project_name }}/manage.py migrate
  with_items:
    - "{{ services }}"
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: commit code
  command: "{{ item }}"
  with_items:
    - cd {{ project_root }}/{{ project_name }}/
    - git add .
    - git commit -m "updated models by inspect db command by trainman"
    - git push
  tags:
    - trellioadmin