---

- name: Install postgres
  include: roles/postgres/tasks/main.yml
  tags:
    - setup
    - postgres

- name: trellioadmin copy settings.py
  template: src=settings.py.j2 dest={{ project_root }}/{{ project_name }}/{{ project_name }}/settings.py
  sudo: yes
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: create apps
  shell: |
    source /home/{{ ansible_user }}/venv/bin/activate
    cd {{ project_root }}/{{ project_name }}
    mkdir apps/{{ item.service }}
    python manage.py startapp apps/{{ item.service }}
    python manage.py inspectdb --database={{ item.service }} > apps/{{ item.service }}/models.py
    python manage.py makemigrations
    python manage.py migrate
  sudo: yes
  with_items:
    - "{{ services }}"
  notify:
    - restart uwsgi
  tags:
    - trellioadmin

- name: commit code
  shell: |
    cd {{ project_root }}/{{ project_name }}
    git add .
    git commit -m "updated models by inspect db command by trainman"
    git push
  tags:
    - trellioadmin