---

- name: Install trellio
  include: roles/trellio/tasks/main.yml
  tags:
    - setup
    - service

- name: Installing trellio service - {{ service_name }}
- pip:
    name: git+{{ service_repo_url }}
    editable: false
    virtualenv: $HOME/venv
    virtualenv_python: python3.6
  tags:
    - setup
    - service

- name: install python dependencies
  notify: restart uwsgi
  pip: >
    requirements={{ python_requirements_file }}
    state=present
  sudo: yes
  tags:
    - setup
    - deploy
    - dependencies
