---

- name: Creating .netrc file
  become: yes
  template: src=.netrc.j2 dest=/home/{{ ansible_user }}/.netrc owner=root group=root mode=0664
  tags:
    - setup
    - service


- name: Set permission and ownership to venv
  file: dest=/home/{{ ansible_user }}/venv owner={{ ansible_user }} group={{ ansible_user }} mode=0777 recurse=yes state=directory
  become: yes
  tags:
    - setup
    - service

- name: Installing {{ project_name }}
  pip:
    name={{ item.name }}
    virtualenv=/home/{{ ansible_user }}/venv
    virtualenv_python=python3.6
    editable=false
    state=latest
  with_items:
     - name: git+{{ pip_repo_url }}
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - service
    - deploy

#- name: fixing aiohttp bug
#  shell: /home/{{ ansible_user }}/venv/bin/pip install yarl==0.15.0
#  become_user: "{{ ansible_user }}"
#  tags:
#    - setup
#    - service
#    - deploy

- name: Creating service config.json
  sudo: yes
  template: src=config.json.j2 dest=/home/{{ ansible_user }}/venv/lib/python3.6/site-packages/{{ config_path }} owner="{{ ansible_user }}" group="{{ ansible_user }}" mode=0777
  tags:
    - setup
    - service
    - deploy

- name: Creating service Upstart file
  sudo: yes
  notify:
    - reload systemctl
  template: src=trellio_service.j2 dest=/etc/systemd/system/{{ service_name }}.service owner="{{ ansible_user }}" group="{{ ansible_user }}" mode=0644
  tags:
    - setup
    - service

- name: disable service
  sudo: yes
  command: systemctl disable {{ service_name }}.service
  tags:
    - setup
    - service

- name: re-enable service
  sudo: yes
  command: systemctl enable {{ service_name }}.service
  tags:
    - setup
    - service

- name: restart service
  sudo: yes
  command: service {{ service_name }} restart
  tags:
    - setup
    - service
    - deploy
