---

- name: Creating .netrc file
  become: yes
  template: src=.netrc.j2 dest=/home/{{ ansible_user }}/.netrc owner=root group=root mode=0664
  tags:
    - setup
    - service


- name: Installing {{ project_name }}
  pip:
    name=git+{{ pip_repo_url }}
    virtualenv=/home/{{ ansible_user }}/venv
    virtualenv_python=python3.6
    editable=false
  sudo: yes
  tags:
    - setup
    - service

- name: Creating service config.json
  sudo: yes
  template: src=config.json.j2 dest=/home/{{ ansible_user }}/venv/lib/python3.6/site-packages/{{ service_name }}/config.json owner="{{ ansible_user }}" group="{{ ansible_user }}" mode=0777
  tags:
    - setup
    - service


- name: Creating service Upstart file
  sudo: yes
  notify:
    - reload systemctl
  template: src=trellio_service.j2 dest=/etc/systemd/system/{{ service_name }}.service owner="{{ ansible_user }}" group="{{ ansible_user }}" mode=0644
  tags:
    - setup
    - service

- name: restart service
  sudo: yes
  command: service {{ service_name }} restart
  tags:
    - setup
    - service
