--- 

- name: create root project directory
  file: path={{ project_root }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0777 state=directory
  sudo: yes
  tags:
    - setup
    - deploy

- name: deploy code from repository repo_branch
  git: accept_hostkey=yes repo={{ repo_url }} dest={{ project_root }} remote=origin version=master
  notify:
    - restart uwsgi
  tags:
    - deploy
    - setup

#- name: Fix for pip bug
#  sudo: yes
#  shell: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
#  tags:
#    - setup

- name: Create Virtualenv & upgrade pip
  pip:
     name={{ item.name }}
     virtualenv=/home/{{ ansible_user }}/venv
     virtualenv_python=python3
  with_items:
     - name: pip --upgrade
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - deploy
    - virtualenv

- name: install python dependencies
  notify: restart uwsgi
  pip: >
    requirements={{ project_root }}/{{ project_name }}/requirements.txt
    state=present
  sudo: yes
  tags:
    - setup
    - deploy
    - dependencies



