--- 

- name: Creating .netrc file
  become: yes
  template: src=.netrc.j2 dest=/home/{{ ansible_user }}/.netrc owner=root group=root mode=0664
  tags:
    - setup
    - trellioadmin

- name: create root project directory
  file: path={{ project_root }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0777 state=directory
  sudo: yes
  tags:
    - setup
    - trellioadmin

- name: deploy code from repository repo_branch
  git: repo={{ repo_url }} dest={{ project_root }}/{{ project_name }}
  become_user: "{{ ansible_user }}"
  notify:
    - restart uwsgi
  tags:
    - setup
    - trellioadmin

#- name: Fix for pip bug
#  sudo: yes
#  shell: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
#  tags:
#    - setup
- name: Install python required packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python-dev
    - python-pip
    - python-virtualenv
    - python3-dev
    - python3-pip
    - python3-virtualenv
  sudo: yes
  tags:
    - setup
    - trellioadmin

- name: Create Virtualenv & upgrade pip
  pip:
     name={{ item.name }}
     virtualenv=/home/{{ ansible_user }}/venv
     virtualenv_python=python3
  with_items:
     - name: pip --upgrade
  become_user: "{{ ansible_user }}"
  tags:
    - setup
    - trellioadmin
    - virtualenv

- name: install python dependencies
  notify: restart uwsgi
  pip: >
    virtualenv=/home/{{ ansible_user }}/venv
    requirements={{ project_root }}/{{ project_name }}/requirements.txt
    state=present
  sudo: yes
  tags:
    - setup
    - trellioadmin
    - dependencies



