# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-17 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170217_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487330932, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487330932, null=True),
        ),
    ]
