# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20170217_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.IntegerField(blank=True, default=1487495531, null=True)),
                ('updated_on', models.IntegerField(blank=True, default=1487495531, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('http_server', models.CharField(choices=[('NGINX', 'NGINX')], default='NGINX', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='server',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487495531, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487495531, null=True),
        ),
        migrations.AddField(
            model_name='apigateway',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
        ),
    ]
