# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-21 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20170219_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigateway',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='apigateway',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated_on',
            field=models.IntegerField(blank=True, default=1487672395, null=True),
        ),
    ]
