---

- name: create root project directory
  file: path={{ project_root }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0775 state=directory
  sudo: yes
  tags:
    - setup
    - deploy
    - celery

- name: change project_root permission
  sudo: yes
  shell: chmod 777 {{ project_root }}
  tags:
    - setup
    - deploy
    - celery


- name: deploy code from repository repo_branch
  action: git accept_hostkey=yes repo={{ repo_url }} dest={{ project_root }}/{{ project_name }} remote={{ repo_remote }} version={{ repo_branch }}
  notify:
    - restart celery
  tags:
    - deploy
    - setup
    - celery
    - pull

- name: Install required system packages.
  apt: pkg={{ item }} state=installed
  with_items: system_packages
  sudo: yes
  tags:
    - web
    - deploy
    - setup
    - celery

- name: Fix for pip bug
  sudo: yes
  shell: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
  tags:
    - setup
    - web
    - deploy
    - celery

- name: upgrade pip
  sudo: yes
  shell: easy_install -U pip
  tags:
    - web
    - deploy
    - setup
    - celery


- name: install python dependencies
  sudo: yes
  pip: >
    requirements={{ python_requirements_file }}
    state=present
  tags:
    - web
    - deploy
    - setup
    - celery


- name: Copy celery upstart file
  sudo: yes
  notify: restart celery
  template: src=celery.conf.j2 dest=/etc/init/celery.conf owner=root group=root mode=0755
  tags:
    - deploy
    - setup
    - celery
    - upstart

