---

- name: Create /etc/apt/sources.list.d/nginx.list
  template: src=nginx.list.j2 dest=/etc/apt/sources.list.d/nginx.list
  sudo: yes
  tags:
    - nginx

- name: Add signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present validate_certs=no
  sudo: yes
  tags:
    - nginx

- name: Install Nginx
  apt: pkg={{ item }} state=installed update-cache=yes
  sudo: yes
  with_items:
    - nginx
    - letsencrypt
  tags:
    - nginx

- name: Copy nginx.conf file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes
  notify:
    - restart nginx
  tags:
    - nginx

- name: Remove conf.d directory
  file: path=/etc/nginx/conf.d state=absent
  sudo: yes
  tags:
    - nginx

- name: update fastcgi_param file
  template: src=fastcgi_params.j2 dest=/etc/nginx/fastcgi_params
  sudo: yes
  notify:
    - restart nginx
  tags:
    - nginx

- name: Create snippets directory
  file: path=/etc/nginx/snippets state=directory
  sudo: yes
  tags:
    - nginx

- name: Create site-enabled directory
  file: path=/etc/nginx/sites-enabled state=directory
  sudo: yes
  tags:
    - nginx

- name: Copy ssl.conf file
  template: src=ssl.conf.j2 dest=/etc/nginx/snippets/ssl.conf
  sudo: yes
  notify:
    - restart nginx
  tags:
    - nginx

- name: Copy letsencrypt.conf file
  template: src=letsencrypt.conf.j2 dest=/etc/nginx/snippets/letsencrypt.conf
  sudo: yes
  notify:
    - restart nginx
  tags:
    - letsencrypt
    - nginx

- name: create /var/www/letsencrypt/.well-known/acme-challenge directory
  file: path=/var/www/letsencrypt/.well-known/acme-challenge state=directory
  sudo: yes
  tags:
    - letsencrypt
    - nginx

- name: create temporary domain.conf file
  template: src=domain.conf.j2 dest=/etc/nginx/sites-enabled/domain.conf
  sudo: yes
  notify:
    - restart nginx
  tags:
    - letsencrypt
    - nginx

- name: generate certificate
  shell: letsencrypt certonly --webroot -w /var/www/letsencrypt -d {{ hostname }} --email {{ email }} --agree-tos
  ignore_errors: yes
  sudo: yes
  tags:
    - letsencrypt
    - nginx

- name: Remove temp domain.conf file
  file: path=/etc/nginx/sites-enabled/domain.conf state=absent
  sudo: yes
  notify:
    - restart nginx
  tags:
    - letsencrypt
    - nginx


- name: create trellioadmin.conf file
  template: src=trellioadmin.conf.j2 dest=/etc/nginx/sites-enabled/trellioadmin.conf
  sudo: yes
  notify:
    - reload nginx
  tags:
    - trellioadmin
  ignore_errors: yes

- name: create gateway.conf file
  template: src=gateway.conf.j2 dest=/etc/nginx/sites-enabled/gateway.conf
  sudo: yes
  notify:
    - reload nginx
  tags:
    - gateway
