---

- name: Export LD_LIBRARY_PATH
  shell: export LD_LIBRARY_PATH=/home/{{ ansible_user }}/.local/lib/:$LD_LIBRARY_PATH
  tags:
    - yajl

- name: clone yajl from repository repo_branch
  git: accept_hostkey=yes repo=https://github.com/lloyd/yajl.git dest=/tmp/yajl remote=origin version=master
  tags:
    - yajl

- name: Configure Yajl
  shell: cd /tmp/yajl && ./configure --prefix=/home/{{ ansible_user }}/.local/
  sudo: yes
  tags:
    - yajl

- name: Cmake Yajl
  shell: cd /tmp/yajl && cmake -DCMAKE_INSTALL_PREFIX=/home/{{ ansible_user }}/.local/
  sudo: yes
  tags:
    - yajl

- name: Make Yajl
  shell: cd /tmp/yajl && make
  sudo: yes
  tags:
    - yajl

- name: Make Install Yajl
  shell: cd /tmp/yajl && make install
  sudo: yes
  tags:
    - yajl

- name: Remove old yajl lib
  file:
    state: absent
    path: "/usr/lib/x86_64-linux-gnu/libyajl.so"

- name: Symbolic link Yajl
  shell: ln -s /home/{{ ansible_user }}/.local/lib/libyajl.so.2.1.1 /usr/lib/x86_64-linux-gnu/libyajl.so
  sudo: yes
  tags:
    - yajl
