---

- hosts: all
  roles:
    - common

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - redis

- hosts: service_registry
  roles:
    - trellio
