---

- hosts: all
  roles:
    - common

- hosts: server
  roles:
    - server
    - common

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - redis

- hosts: service_registry
  roles:
    - trellio

- hosts: trellio_admin
  roles:
    - nginx
    - postgres
    - django
    - trellioadmin


