---

#- hosts: all
#  roles:
#    - common

- hosts: trellio_service
  roles:
    - service

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - redis

- hosts: service_registry
  roles:
    - trellio

- hosts: trellio_admin
  roles:
    - nginx
    - uwsgi
    - postgres
    - trellioadmin


