---

#- hosts: all
#  roles:
#    - common

- hosts: server
  roles:
    - server
    - common

- hosts: trellio_service
  roles:
    - service

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - common
    - redis

- hosts: service_registry
  roles:
    - common
    - trellio

#- hosts: trellio_admin
#  roles:
#    - nginx
#    - postgres
#    - django
#    - trellioadmin


