---

#- hosts: all
#  roles:
#    - common

- hosts: trellio_service
  roles:
    - trellio
    - service
    - nginx

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - redis

- hosts: service_registry
  roles:
    - trellio


