---

- hosts: all
  become: yes
  become_user: "{{ ansible_user }}"
  roles:
    - common

- hosts: trellio_service
  roles:
    - trellio
    - service

- hosts: gateway
  roles:
    - nginx


- hosts: postgres
  roles:
    - postgres


- hosts: redis
  roles:
    - redis

- hosts: service_registry
  roles:
    - trellio



- hosts: devops
  roles:
    - uwsgi
    - nginx